### ISSUE TITLE
Would it be possible to implement Tiered mod compatibility?

### ISSUE THREAD

**Issue by Jacob1101** [ZsoltMolnarrr/Archers#13]
Tiered adds a rerolling system that you can use to get better weapons. For some reason, all of the new range weapons require flint to be rerolled instead of their respective metal, which is extremely overpowered. This means you can reroll a heavy netherite crossbow until you get a legendary one, costing nothing but flint. This is obviously way easier than rerolling a netherite sword for example, which takes one netherite ingot every time, and so is very unbalanced. Thank you!

**Comment by ZsoltMolnarrr** [comment]
Likley not possible since, it introduces its own ranged attack damage attribute, instead of using Projectile Damage Attribute.
