### ISSUE TITLE
After death my Arcane Tome, Paladin Libram, Holy Book and any other tomes change to Archery Manual

### ISSUE THREAD

**Issue by SamRedFox** [ZsoltMolnarrr/Archers#15]
Every time I die my Arcane Tome, Paladin Libram, Holy Book and any other tomes change to Archery Manual with all 3 spells upgrage. It happens all the time and I already have plenty of useless Archery Manuals. This happen only to me as a server creator, my friends conned to my game don't experience this issue

**Comment by ZsoltMolnarrr** [comment]
I don't think this is possible without conflicting mods.
What is the absolute minimal setup to reproduce this?

**Comment by ZsoltMolnarrr** [comment]
Please specify, otherwise this issue is non-actionable.

**Comment by SamRedFox** [comment]
Well, It's kinda hard to tell what mods might cause a conflict, but I can tell that I use all the mods from RPG series, including jewelry which also has issues. My rings and necklaces dissapear after death and maybe after game restart. I also noticed that this duplication issue happens with other tomes from wizards or paladins. Also, when I remove any tome from the tome slot and go into nether portal, I still have a duplicated tome texture in the slot after teleporting, which disappears after clicking on it. 
1.20.1
Forge 47.1.3
Sinytra Connector (I hope is not causing the issue)
Forgified Fabric API
All RPG series mods (required libraries included)
better combat
combatroll
The Twilight Forest
Divine RPG
The Aether
journey map
JEI

**Comment by ZsoltMolnarrr** [comment]
This issue does not occur on the Fabric installation.
Can you please try to update to the latest Sinytra Connector and report back?
