### ISSUE TITLE
Crossbow Infinity can fire tipped arrows without consuming them

### ISSUE THREAD

**Issue by Partonetrain** [ZsoltMolnarrr/Archers#16]
Definitely overpowered, I assume unintended.

https://github.com/ZsoltMolnarrr/Archers/assets/19861808/3ab19b9b-f4a9-4225-99fb-31af22201c2c

**Comment by ZsoltMolnarrr** [comment]
Well, how does the same thing work for bows?

**Comment by Partonetrain** [comment]
Infinity Bows consume spectral and tipped arrows when firing them.

**Comment by ZsoltMolnarrr** [comment]
Will be released soon. :)
