### ISSUE TITLE
Weird crash with Archers and Gazebo installed together

### ISSUE THREAD

**Issue by crabinpenguin** [ZsoltMolnarrr/Archers#17]
Hi, I'm making my own custom modpack in Modrinth at the moment and for some reason when I have both Archers and Gazebo installed, I crash with a mixins error. I am also using CTOV, and with just archers no gazebos generate, but if I have CTOV Gazebo Compat, far too many generate, and I dont see a setting for this in the Archers config, despite there being a setting for it in the Gazebo config.
[crash-2023-12-13_08.25.30.6485-quilt_loader.txt]
(https://github.com/ZsoltMolnarrr/Archers/files/13662482/crash-2023-12-13_08.25.30.6485-quilt_loader.txt)

**Comment by ZsoltMolnarrr** [comment]
Quilt is not officially supported. You may experiment with on your on behalf, but I cannot help when something goes wrong.
