### ISSUE TITLE
Balance issues

### ISSUE THREAD

**Issue by Partonetrain** [ZsoltMolnarrr/Archers#18]
I brought this up in the discord, but I'm putting it here so it doesn't get lost.

- One would expect the weapons with longer pull times to fire arrows at a greater velocity (and have a larger range as a result), but all Archers weapons have the default velocity.

- The Composite Longbow and Mechanical Shortbow have the same Projectile Damage stat, but different pull times. Shouldn't Mechanical Shortbow's damage be lower since it takes less time to pull? As it stands, Mechanical Shortbow is just superior.

Stats from https://github.com/ZsoltMolnarrr/Archers/blob/1.20.1/src/main/java/net/archers/item/Weapons.java#L114-L153

**Comment by ZsoltMolnarrr** [comment]
I disagree with the expectation. My primary reference point is Minecraft Dungeons, where different ranged weapons don't have different ranges.

However it is possible to configure weapons individually to match your expectations, by just adding the `"velocity"` field. This does not effect the damage, only the arrow velocity.
```
    "archers:netherite_heavy_crossbow": {
      "pull_time": 35,
      "damage": 16.0,
      "velocity": 4
    },
```
