### ISSUE TITLE
[Crash] one of my players on my server crashes when equipping some of the mods gear

### ISSUE THREAD

**Issue by tiigerbones** [ZsoltMolnarrr/Archers#19]
heres are the logs

<html>
<body>

[19:36:27] [Render thread/WARN]: Failed to load texture: minecraft:textures/models/armor/archer_armor_layer_1.png
--
8578 | java.io.FileNotFoundException: minecraft:textures/models/armor/archer_armor_layer_1.png
8579 | at net.minecraft.resource.ResourceFactory.method_43043(ResourceFactory.java:21) ~[client-intermediary.jar:?]
8580 | at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
8581 | at net.minecraft.resource.ResourceFactory.getResourceOrThrow(ResourceFactory.java:21) ~[client-intermediary.jar:?]
8582 | at mod.azure.azurelib.cache.texture.AnimatableTexture.method_4625(AnimatableTexture.java:41) ~[azurelib-fabric-1.20.1-2.0.18.jar:?]
8583 | at net.minecraft.client.texture.TextureManager.loadTexture(TextureManager.java:97) ~[client-intermediary.jar:?]
8584 | at net.minecraft.client.texture.TextureManager.registerTexture(TextureManager.java:69) ~[client-intermediary.jar:?]
8585 | at net.minecraft.client.texture.TextureManager.handler$bdn000$azurelib$wrapAnimatableTexture(TextureManager.java:530) ~[client-intermediary.jar:?]
8586 | at net.minecraft.class_1060.method_4619(class_1060.java) ~[client-intermediary.jar:?]
8587 | at traben.entity_texture_features.utils.ETFUtils2.getNativeImageElseNull(ETFUtils2.java:214) ~[entity_texture_features_fabric_1.20.1-5.1.2.jar:?]
8588 | at traben.entity_texture_features.features.texture_handlers.ETFTexture.reRegisterBaseTexture(ETFTexture.java:429) ~[entity_texture_features_fabric_1.20.1-5.1.2.jar:?]
8589 | at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.modify$dak000$entity_texture_features$etf$changeTexture2(ArmorFeatureRenderer.java:5065) ~[client-intermediary.jar:?]
8590 | at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmorParts(ArmorFeatureRenderer.java:118) ~[client-intermediary.jar:?]
8591 | at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.renderArmor(ArmorFeatureRenderer.java:75) ~[client-intermediary.jar:?]
8592 | at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer.java:44) ~[client-intermediary.jar:?]
8593 | at net.minecraft.client.render.entity.feature.ArmorFeatureRenderer.render(ArmorFeatureRenderer.java:27) ~[client-intermediary.jar:?]
8594 | at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer.java:145) ~[client-intermediary.jar:?]
8595 | at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer.java:66) ~[client-intermediary.jar:?]
8596 | at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer.java:43) ~[client-intermediary.jar:?]
8597 | at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:145) ~[client-intermediary.jar:?]
8598 | at net.minecraft.client.gui.screen.ingame.InventoryScreen.method_29977(InventoryScreen.java:151) ~[client-intermediary.jar:?]
8599 | at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1191) ~[client-intermediary.jar:?]
8600 | at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawEntity(InventoryScreen.java:151) ~[client-intermediary.jar:?]
8601 | at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawEntity(InventoryScreen.java:128) ~[client-intermediary.jar:?]
8602 | at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawBackground(InventoryScreen.java:105) ~[client-intermediary.jar:?]
8603 | at net.minecraft.client.gui.screen.ingame.HandledScreen.render(HandledScreen.java:100) ~[client-intermediary.jar:?]
8604 | at net.minecraft.client.gui.screen.ingame.AbstractInventoryScreen.render(AbstractInventoryScreen.java:27) ~[client-intermediary.jar:?]
8605 | at net.minecraft.client.gui.screen.ingame.InventoryScreen.render(InventoryScreen.java:88) ~[client-intermediary.jar:?]
8606 | at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:110) ~[client-intermediary.jar:?]
8607 | at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945) ~[client-intermediary.jar:?]
8608 | at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219) ~[client-intermediary.jar:?]
8609 | at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802) ~[client-intermediary.jar:?]
8610 | at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.15.3.jar:?]
8611 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
8612 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
8613 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]

</body>
</html>

**Comment by ZsoltMolnarrr** [comment]
Unable to reproduce the issue.
I am fairly certain this is an server-client version/installation mismatch issue.
