### ISSUE TITLE
Unable to use Archery Spells

### ISSUE THREAD

**Issue by MechanosG** [ZsoltMolnarrr/Archers#22]
Basically...  spell engine wants to use the "use" key, which defaults to right click.  But bows/crossbows use the use key/right click to fire.  The bow/crossbow firing seems to always take priority over spell casting, even if you enable the "use key priority" option in spell engine.  If I change the use key, I can use archery spells via the new key.  But then I have to remove "use" from right click, which..  feels incredibly awkward, and kind of a deal breaker.

Is there a way around this?  Am I missing something?  I'm using the Prominence II [RPG] modpack on a friend's multiplayer server, version 2.5.0 (haven't updated to the latest yet).

**Comment by ZsoltMolnarrr** [comment]
Can you name a specific example where this is practically a problem?
It is difficult to find out what you are actually looking for.

**Comment by MechanosG** [comment]
I thought it was pretty self explanatory, but my bad.  I have a bow and a crossbow.  I have an Archery Manual with Power Shot equipped.  I'm completely unable to use Power Shot with the bow and crossbow, unless I rebind my use key.  Rebinding my use key, makes it so that I am unable to open chests, doors, interact with blocks, etc, with right click anymore.  This is very practically, a problem.  I feel many players would not want to give up right click interaction.

The ideal fix, would be spell casting taking priority, so that right clicking with a bow uses the spell if it's available, but fires normally if it's on cooldown.  Or alternatively, being able to cast archery spells with a different key, without having to change the "use key" key bind, so that I can still use right click to interact with things as normal.  But before I made these suggestions, I wanted to ask and make sure I wasn't missing something.

**Comment by ZsoltMolnarrr** [comment]
This is a consequence of a technical limitation of how Minecraft internal item use works.
This issue is completely non actionable.
