### ISSUE TITLE
1.20.1 latest archers affects banner patterns from other mods

### ISSUE THREAD

**Issue by vivagabe** [ZsoltMolnarrr/Archers#24]
Im using Sinytra Connector with Ice and Fire (which adds banner patterns). When archers is installed, the banner patterns are blank. i understand this is a very niche issue but hopefully a simple fix.

**Comment by Partonetrain** [comment]
very strange considering Archers doesn't touch banners in any way

**Comment by ZsoltMolnarrr** [comment]
Is this still an issue with the latest versions?

**Comment by vivagabe** [comment]
EDIT: Unfortunately banners still not working. Found also have a new issue where i crash when trying to equip a weapon. will create another issue.
