### ISSUE TITLE
Crash when equipping weapon (using Sinytra connector)

### ISSUE THREAD

**Issue by vivagabe** [ZsoltMolnarrr/Archers#26]
When i try to equip a weapon, the game crashes.
[crash-2024-04-04_21.12.09-client.txt](https://github.com/ZsoltMolnarrr/Archers/files/14879736/crash-2024-04-04_21.12.09-client.txt)

**Comment by ZsoltMolnarrr** [comment]
Trinkets mod seems to be tampered with.
Either use original version, or remove it.

**Comment by ZsoltMolnarrr** [comment]
In my SinytraConnector test modpack, there is no such crash, as I use original release of trinkets.
This issue non actionable from my side, I am affraid.

Feel free to reopen if there is a specific technical recommendation.
