### ISSUE TITLE
Vanilla bow and crossbow tooltip has "projectile damage" instead of "ranged damage"

### ISSUE THREAD

**Issue by Partonetrain** [ZsoltMolnarrr/Archers#28]
The relevant code is actually in [Projectile Damage Attribute](https://github.com/ZsoltMolnarrr/ProjectileDamage/blob/2497cc9c09ba85ba196333a1931dcd71e24d3e0e/common/src/main/java/net/projectile_damage/internal/RegistryHelper.java#L18) but I would expect vanilla items to use the attributes that Archers weapons use

Shouldn't Projectile Damage Attribute be deprecated?

**Comment by ZsoltMolnarrr** [comment]
PDA is fully deprecated, still many players are known to be relying on it.
Hence in its latest update, it isn't deleted entirely, instead gives priority to RWA.
Do you experience the issue with PDA updated?

**Comment by Partonetrain** [comment]
So, turns out they use ranged damage _only if_ PDA is installed. Without it, they use projectile damage tooltip. 
I was under the impression PDA was in Jar-in-jar for RWA but that doesn't seem to be the case.
Still, I don't think they should use "projectile damage" when PDA is not installed.

**Comment by ZsoltMolnarrr** [comment]
If all mods are fully up to date, PDA should give priority to RWA :)

**Comment by Partonetrain** [comment]
Upon further inspection, one of my mods has an outdated PDA jar-in-jar.
