### ISSUE TITLE
Crash with Supplementaries, Archers, and any mod that adds new banner patterns (using Sinytra Connector)

### ISSUE THREAD

**Issue by vivagabe** [ZsoltMolnarrr/Archers#31]
[crash-2024-05-16_19.44.07-server.txt](https://github.com/ZsoltMolnarrr/Archers/files/15343035/crash-2024-05-16_19.44.07-server.txt)

Get a crash when loading into a world. I contacted the Supplementaries dev and he said: Some mod is messing up the sheets class
Not supplementaries issue. That's written in the log

Hopefully an easy fix.

**Comment by ZsoltMolnarrr** [comment]
There is nothing in this crashlog I can see that points to "Archers" or any other of my mods causing the problem.
I am unsure what is causing your crash.

**Comment by vivagabe** [comment]
Ok thank you! i was told that the "sheet classes" were being loaded too early (im too dumb to understand) but if archers doesnt affect that then i'll keep looking.

**Comment by abby-cadabra** [comment]
Realise this report is closed, but apparently this issue is caused by Sinytra. It is fixed in the latest indev version.
