### ISSUE TITLE
Updating tooltips after editing config

### ISSUE THREAD

**Issue by VitaminJake** [ZsoltMolnarrr/Archers#33]
Hello, I could just be an idiot and not know this, but after editing config values for bows' damage or armor values, how can I cause the tooltip in game to update? Is this built into the lore NBT of the item? I'm still pretty new to commands and modding but trying to learn. 

The reason I had to make changes to the config is that I find it _far_ easier to get Ruby and Cinncinasite from BetterNether than it is to get netherite, and so therefore I feel the damage from Ruby gear should be less.
![Base Profile Screenshot 2024 06 20 - 13 33 11 34](https://github.com/ZsoltMolnarrr/Archers/assets/162518177/d2fd8f27-eced-427a-a6f0-c6922877ee40)

**Comment by ZsoltMolnarrr** [comment]
As the project site describes, the attribute of these items is configurable.

Ruby crossbows will be reworked to be upgrades from Netherite variants.

**Comment by ZsoltMolnarrr** [comment]
Fixed in Archer 1.2.3

**Comment by VitaminJake** [comment]
I'm really sorry to bother you again, I know you probably are insanely busy to answer these questions. I know the attribute can be modified - I've gotten into the config and changed the damage values. But is it possible to make it so the tooltip in-game (when someone mouses over the bow) will display the newly configured values? Also thanks so much for that update to the recipes, much love for all your work.

**Comment by ZsoltMolnarrr** [comment]
Server and client need to have the same config file.
To solve this I recommend making Modpacks using the CurseForge app, and distributing the exported modpack (to other players) that contains all mods and configs.
