### ISSUE TITLE
Archers Update/Spell Engine/SimplySkills compatibility issue

### ISSUE THREAD

**Issue by VitaminJake** [ZsoltMolnarrr/Archers#34]
The new Archers update is not possible to launch. It won't launch with any version of Spell Engine and SimplySkills. 

(With 14.3 installed)
![Screenshot 2024-06-22 114304](https://github.com/ZsoltMolnarrr/Archers/assets/162518177/69f1515b-4c4d-4322-9133-20f00be4fc2f)

(With 15.0 installed, and also with 15+)
![Screenshot 2024-06-22 114346](https://github.com/ZsoltMolnarrr/Archers/assets/162518177/bf4f67cd-18ea-4950-b683-a2f450fc34c5)

**Comment by ZsoltMolnarrr** [comment]
The error literally says what needs to be done.
Simply Skills needs to be updated or disabled.

**Comment by VitaminJake** [comment]
So you're saying you no longer support simplyskills? It's the latest version. There is no update. 
![image_2024-06-22_192739617](https://github.com/ZsoltMolnarrr/Archers/assets/162518177/b1d0cc8f-ce88-4675-8b4d-9568b63c0d9a)
