### ISSUE TITLE
book slot does not show 

### ISSUE THREAD

**Issue by luluthepogcat** [ZsoltMolnarrr/Archers#37]
![image](https://github.com/ZsoltMolnarrr/Archers/assets/154001303/63e3a8ee-619e-4dd0-a55b-beb4c33f1e35)
the book slot on forge version used with sinytra connector doesnt exist (on the image im just holding the book and hover it over the place of the book slot)
![image](https://github.com/ZsoltMolnarrr/Archers/assets/154001303/d8afbd1a-c810-42f0-8d25-ad0797c66723)
here is my mod file

**Comment by ZsoltMolnarrr** [comment]
Trinkets mod is not installed.

:pray: Please do not attempt installing mods with manual drag&drop (Windows Explorer). (Modern mods require many libraries, the dependency relation of which can be complicated, requiring lots of digging what to install). 
:gift: Instead, use a proper Minecraft launcher app. These can install mods for you with a single click, and resolve all dependencies automatically.
Recommended apps:
- CurseForge official app https://download.curseforge.com
- Modrinth official app https://modrinth.com/app

**Comment by luluthepogcat** [comment]
> Trinkets mod is not installed.
> 
> 🙏 Please do not attempt installing mods with manual drag&drop (Windows Explorer). (Modern mods require many libraries, the dependency relation of which can be complicated, requiring lots of digging what to install). 🎁 Instead, use a proper Minecraft launcher app. These can install mods for you with a single click, and resolve all dependencies automatically. Recommended apps:
> 
> * CurseForge official app https://download.curseforge.com
> * Modrinth official app https://modrinth.com/app

thank you, its just curseforge wont show the mod in the first place because it thinks it only works on fabric, so i have to find the mods and install them manually
![image](https://github.com/ZsoltMolnarrr/Archers/assets/154001303/45375009-3216-47d9-a9ca-84dc9190376d)

**Comment by ZsoltMolnarrr** [comment]
![345847990-45375009-3216-47d9-a9ca-84dc9190376d](https://github.com/ZsoltMolnarrr/Archers/assets/4989469/83ae5e97-ed09-4705-b491-73e4def9f7a0)

Uncheck `Forge` filter

**Comment by luluthepogcat** [comment]
learn new things everyday
