### ISSUE TITLE
Gives ways for archers to combat projectile-resistant mobs

### ISSUE THREAD

**Issue by LonelyMusicDisc** [ZsoltMolnarrr/Archers#38]
It makes sense why some mobs being able to block arrows isn't a big deal (like endermen or the evoker), because in the vanilla game the bow is just one of the many tools you're meant to use all of. It becomes a problem when your entire play style is centered around arrows and bow skills you spend a lot of time honing.

Also for fairness sake, the wizard can use their magic the entire game because they can hurt endermen with their projectiles and burn blazes with its fire.

**Comment by ZsoltMolnarrr** [comment]
Spears, roots, magic arrow.
