### ISSUE TITLE
Simple Quiver compat

### ISSUE THREAD

**Issue by Sansukan** [ZsoltMolnarrr/Archers#39]
The Bow does take arrows from the quiver.
But the archery skills don't. So you cant use your skills whit the quiver equipped unless you carry more arrows in the inventory apart from the quiver.

**Comment by ZsoltMolnarrr** [comment]
Sorry, no thank you.
Simple Quiver has low quality artwork, uses non-sense material tiers.
Adding compact would be very difficult.
Supplmentaries quiver is supported already.
