### ISSUE TITLE
Archer and Ranger arm texture issue

### ISSUE THREAD

**Issue by Mozork01** [ZsoltMolnarrr/Archers#4]
Little shoulder texture issue
archers-1.0.3+1.20.1

![2023-11-09_13 46 58](https://github.com/ZsoltMolnarrr/Archers/assets/148884018/9b315e80-1353-4df6-af33-1c5586bdb07a)
![2023-11-09_13 48 57](https://github.com/ZsoltMolnarrr/Archers/assets/148884018/d807ca10-8ca3-4dad-859d-1ee471f5e08a)

**Comment by ZsoltMolnarrr** [comment]
Fix will be available in 1.0.4
