### ISSUE TITLE
Bows won't load in survival

### ISSUE THREAD

**Issue by F1R3B1RD7** [ZsoltMolnarrr/Archers#40]
I love this mod and have it installed in a modpack, however I noticed that in survival the bows/crossbows will not load an arrow, it works fine in creative (and yes I do have arrows in my inventory) I'm assuming this is an incompatability with another mod since I experimented with an istallation dedicated to this and it worked just fine so I'm wondering if this is a known bug or anyone has a workaround, Thanks :)

**Comment by ZsoltMolnarrr** [comment]
It is strongly recommended to use a proper launcher for installing mods (such as CurseForge app).
This resolves required mods automatically.
