### ISSUE TITLE
[1.20.1][Connector b45] Crash when hovering over weapons (mainly bows)

### ISSUE THREAD

**Issue by Carsonated** [ZsoltMolnarrr/Archers#41]
Possible Apothic Attributes incompat?

[crash-2024-09-09_07.09.48-client.txt](https://github.com/user-attachments/files/16930211/crash-2024-09-09_07.09.48-client.txt)

**Comment by ZsoltMolnarrr** [comment]
I am sorry I have no idea what exactly is the source of the crash.
It is very complicated.

**Comment by Carsonated** [comment]
Any way I could help? I can send the pack or any other logs

**Comment by Carsonated** [comment]
I found the mod that causes the crash, it's Ranged Weapon API. Not sure exactly why because the logs won't spit out the exact cause

**Comment by Carsonated** [comment]
I found the mod that causes the crash, which is semi-related, it's Ranged Weapon API. Not sure exactly why because the logs won't spit out the exact cause. Going to the reports page for that solved the problem with unionlib (which I don't know why that was even installed because nothing uses it). Thank you for trying to help though!

**Comment by ZsoltMolnarrr** [comment]
Thank you for the response. Sorry that I was unable to provide more meaningful help.

**Comment by Carsonated** [comment]
> Thank you for the response. Sorry that I was unable to provide more meaningful help.

That's perfectly fine and doing a long binary search in the end figured out the problem and solved it, now it's working flawlessly as are the other class mods (though warrior has a black missing texture box which might be a Spell Engine problem because it happens with another class someone else made too). Thank you for putting your effort and time in these mods
