### ISSUE TITLE
"Barrage" Uses extra arrows 

### ISSUE THREAD

**Issue by AvaAsUsual** [ZsoltMolnarrr/Archers#42]
Whenever "consume_item" in 
  "cost": {
    "item_id": "arrow",
    "consume_item": false,
    "cooldown_duration": 10
  }
}

is set to "true", a fourth arrow will be used, resulting in 3 shots that cost 4 arrows
![image_2024-09-24_071234677](https://github.com/user-attachments/assets/c906f3b9-ec34-4f43-b80d-24ae27abcb9c)

How to recreate:
Make a new instance and install archers
Make a datapack to set "consume_item" to true
Enter a world, enchant an archers manual, and use "Barrage"
See that four arrows were taken from your inventory, but only three are on the floor that can be retrieved

**Comment by AvaAsUsual** [comment]
[archers datapack.zip](https://github.com/user-attachments/files/17113652/archers.datapack.zip)
This is my datapack if you need a quick example, but it also will remove "Roots" and "Magic Arrow" from the ability list, so don't worry about that if it ends up confusing you

**Comment by ZsoltMolnarrr** [comment]
Upon reivewing the details I can tell you everything works as expected.
If you don't want the spell cost item to be actually deducted upon casting, than don't use such datapack. :)
