### ISSUE TITLE
[Minecraft 1.20.1 - Fabric 0.16.9] Crash when using Supplementaries mod, due to Quiver.

### ISSUE THREAD

**Issue by Dralaon** [ZsoltMolnarrr/Archers#47]
I detailed everything here: https://github.com/MehVahdJukaar/Supplementaries/issues/1255#issuecomment-2508910685

**Comment by ZsoltMolnarrr** [comment]
This is a known issue of Spell Engine, closing this as is duplicate.
https://github.com/ZsoltMolnarrr/SpellEngine/issues/88
