### ISSUE TITLE
spell bind show gibberish

### ISSUE THREAD

**Issue by jamshieu** [ZsoltMolnarrr/Archers#48]
![2024-12-23_12 56 53_4](https://github.com/user-attachments/assets/4bd67b99-ccbc-4cf8-987a-adea83562ea2)

**Comment by ZsoltMolnarrr** [comment]
![Screenshot 2024-12-23 at 12 13 24](https://github.com/user-attachments/assets/4072ffd7-0db6-4217-a154-33dda546e748)
