### ISSUE TITLE
Error in logs: Failed to resolve weapon attributes

### ISSUE THREAD

**Issue by LeoDemitori** [ZsoltMolnarrr/Archers#8]
Error In logs server/client. 
Will this bug affect the game?

Version Fabric: 0.14.24
Game version: 1.20.1
Mod version: 1.0.3

[archery.txt](https://github.com/ZsoltMolnarrr/Archers/files/13323031/archery.txt)

**Comment by ZsoltMolnarrr** [comment]
Hello what version of Better Combat are you using?

**Comment by LeoDemitori** [comment]
> Hello what version of Better Combat are you using?

1.7.4

**Comment by ZsoltMolnarrr** [comment]
You need to update my friend!
